const sampleListings = [
  {
    title: "Beachfront Cottage in Goa",
    description: "Relax at this peaceful beachfront cottage located steps away from Goa’s serene beaches.",
    image: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg",
    price: 2500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Modern Apartment in Mumbai",
    description: "Luxurious high-rise apartment with stunning skyline views.",
    image: "https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg",
    price: 3500,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Himalayan Retreat in Manali",
    description: "Cozy wooden cottage surrounded by Himalayan peaks.",
    image: "https://images.pexels.com/photos/2773916/pexels-photo-2773916.jpeg",
    price: 2000,
    location: "Manali",
    country: "India",
  },
  {
    title: "Heritage Haveli in Jaipur",
    description: "Experience royal living in an authentic Rajasthani haveli.",
    image: "https://images.pexels.com/photos/1796723/pexels-photo-1796723.jpeg",
    price: 4000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Luxury Houseboat in Alleppey",
    description: "Sail through Kerala’s backwaters in a private luxury houseboat.",
    image: "https://images.pexels.com/photos/261187/pexels-photo-261187.jpeg",
    price: 5000,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Cliffside Villa in Kasol",
    description: "Riverside villa surrounded by tall pine forests.",
    image: "https://images.pexels.com/photos/755385/pexels-photo-755385.jpeg",
    price: 2200,
    location: "Kasol",
    country: "India",
  },
  {
    title: "Desert Camp in Jaisalmer",
    description: "Luxury tents with camel safaris & cultural evenings.",
    image: "https://images.pexels.com/photos/991422/pexels-photo-991422.jpeg",
    price: 3000,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Tea Estate Bungalow in Munnar",
    description: "Colonial bungalow inside lush tea plantations.",
    image: "https://images.pexels.com/photos/257360/pexels-photo-257360.jpeg",
    price: 2800,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Lake View Cottage in Nainital",
    description: "Cottage with enchanting views of Nainital Lake.",
    image: "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
    price: 1800,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Backwater Resort in Kumarakom",
    description: "Waterfront villa in Kerala’s famous backwaters.",
    image: "https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg",
    price: 4500,
    location: "Kumarakom",
    country: "India",
  },
  {
    title: "Hilltop Cabin in Ooty",
    description: "A wooden cabin surrounded by misty hills.",
    image: "https://images.pexels.com/photos/258192/pexels-photo-258192.jpeg",
    price: 2300,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Penthouse in Bengaluru",
    description: "Modern penthouse with premium interiors.",
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    price: 3200,
    location: "Bengaluru",
    country: "India",
  },
  {
    title: "Riverfront Resort in Rishikesh",
    description: "Peaceful retreat with mountain & river views.",
    image: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
    price: 2600,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Forest Treehouse in Lonavala",
    description: "Unique treehouse stay in dense forest.",
    image: "https://images.pexels.com/photos/355321/pexels-photo-355321.jpeg",
    price: 3500,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Luxury Villa in Pune",
    description: "A premium villa with private pool.",
    image: "https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg",
    price: 5000,
    location: "Pune",
    country: "India",
  },
  {
    title: "Cliff View Bungalow in Mahabaleshwar",
    description: "Scenic bungalow overlooking valleys.",
    image: "https://images.pexels.com/photos/259863/pexels-photo-259863.jpeg",
    price: 2200,
    location: "Mahabaleshwar",
    country: "India",
  },
  {
    title: "Beach Hut in Gokarna",
    description: "Seaside hut with palm-tree surroundings.",
    image: "https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg",
    price: 1200,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Island Retreat in Andaman",
    description: "Private villa near crystal-clear beaches.",
    image: "https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg",
    price: 6000,
    location: "Havelock Island",
    country: "India",
  },
  {
    title: "Snow View Cottage in Shimla",
    description: "Charming cottage offering snow-clad views.",
    image: "https://images.pexels.com/photos/1122410/pexels-photo-1122410.jpeg",
    price: 2000,
    location: "Shimla",
    country: "India",
  },
  {
    title: "French Heritage House in Pondicherry",
    description: "White Town French-style heritage stay.",
    image: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    price: 2600,
    location: "Pondicherry",
    country: "India",
  },

  /* --- Now adding 25 MORE listings to reach 45 --- */

  {
    title: "Coastal Villa in Daman",
    description: "Serene villa near Daman's quiet beaches.",
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    price: 2700,
    location: "Daman",
    country: "India",
  },
  {
    title: "Hill Cottage in Darjeeling",
    description: "Cottage overlooking tea gardens.",
    image: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
    price: 2400,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Lake Resort in Udaipur",
    description: "Romantic lakeside stay near Pichola.",
    image: "https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg",
    price: 4200,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Palm Grove Cottage in Varkala",
    description: "Cliffside cottage with beach access.",
    image: "https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg",
    price: 1800,
    location: "Varkala",
    country: "India",
  },
  {
    title: "City Studio in Chennai",
    description: "Business-friendly stay near Marina Beach.",
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
    price: 2000,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Eco Hut in Coorg",
    description: "Eco-friendly hut inside coffee estates.",
    image: "https://images.pexels.com/photos/1438387/pexels-photo-1438387.jpeg",
    price: 1900,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Forest Bungalow in Wayanad",
    description: "Stay inside dense Kerala forests.",
    image: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg",
    price: 2100,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Seaside Villa in Vizag",
    description: "Villa with direct beach access.",
    image: "https://images.pexels.com/photos/2373201/pexels-photo-2373201.jpeg",
    price: 2300,
    location: "Visakhapatnam",
    country: "India",
  },
  {
    title: "Mountain Resort in Gangtok",
    description: "Sikkim mountain view premium resort.",
    image: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
    price: 3500,
    location: "Gangtok",
    country: "India",
  },
  {
    title: "Backpackers Hostel in Dharamshala",
    description: "Affordable hostel with mountain view.",
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
    price: 800,
    location: "Dharamshala",
    country: "India",
  },
  {
    title: "Golden Desert Villa in Bikaner",
    description: "Luxury stay near sand dunes.",
    image: "https://images.pexels.com/photos/991422/pexels-photo-991422.jpeg",
    price: 3200,
    location: "Bikaner",
    country: "India",
  },
  {
    title: "Beachfront Apartment in Kochi",
    description: "Stay near Fort Kochi beach.",
    image: "https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg",
    price: 2600,
    location: "Kochi",
    country: "India",
  },
  {
    title: "Valley Resort in Kodaikanal",
    description: "Boutique stay facing lush valleys.",
    image: "https://images.pexels.com/photos/259862/pexels-photo-259862.jpeg",
    price: 2400,
    location: "Kodaikanal",
    country: "India",
  },
  {
    title: "Luxury Camp in Spiti Valley",
    description: "Premium tents amidst dramatic landscapes.",
    image: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
    price: 3300,
    location: "Spiti",
    country: "India",
  },
  {
    title: "City Apartment in Hyderabad",
    description: "Modern flat in the city center.",
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    price: 2600,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Mountain Stay in Kutch",
    description: "Village-style mud house near white desert.",
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    price: 1400,
    location: "Kutch",
    country: "India",
  },
  {
    title: "Riverside Camp in Haridwar",
    description: "Tent stay beside Ganga river.",
    image: "https://images.pexels.com/photos/991422/pexels-photo-991422.jpeg",
    price: 1700,
    location: "Haridwar",
    country: "India",
  },
  {
    title: "Jungle Retreat in Pench",
    description: "Stay at a forest resort near tiger reserve.",
    image: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg",
    price: 3200,
    location: "Pench",
    country: "India",
  },
  {
    title: "Lake House in Bhopal",
    description: "Stay beside Upper Lake with sunrise view.",
    image: "https://images.pexels.com/photos/2373201/pexels-photo-2373201.jpeg",
    price: 2100,
    location: "Bhopal",
    country: "India",
  },
  {
    title: "Beach Villa in Diu",
    description: "Peaceful villa near Nagoa Beach.",
    image: "https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg",
    price: 2800,
    location: "Diu",
    country: "India",
  },
  {
    title: "Cabin Stay in Mussoorie",
    description: "Beautiful hilltop cabin stay.",
    image: "https://images.pexels.com/photos/1122410/pexels-photo-1122410.jpeg",
    price: 2400,
    location: "Mussoorie",
    country: "India",
  },
  {
    title: "Luxury Palace Stay in Udaipur",
    description: "Royal suite inside heritage palace.",
    image: "https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg",
    price: 9500,
    location: "Udaipur",
    country: "India",
    owner:'6962a1bc665799670268429d'
  }
];

module.exports = { data: sampleListings };
